name: Release Drafter

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@67e173cadb2fbd3de94f4a861e0c48c913b462ae # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
